import 'package:http/http.dart' as http;
//import 'package:manipulacao/models/autoGenerate.dart';

const baseUrl = "http://192.168.0.9:8091";

class Api {
  static Future getProdutos() async {
    return await http.get(baseUrl + "/estoque");
  }
}

class ApiTipoItens {
  static Future getTipos() async {
    return await http.get(baseUrl + "/tiposItem");
  }
}

/*void save(AutoGenerated gerador) {
  http.post(
    baseUrl + "/estoque",
    headers: {'Content-type': 'application/json'},
  );
}
*/
